name: Pylint workflow

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      out:
        required: true
        type: string

jobs:
  build_and_lint:
    name: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Linting
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}
          # python manage.py migrate
          pylint --output-format=json ${{inputs.path }} > ${{inputs.out}}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.out}}
          path: ${{ github.workspace }}/${{inputs.out}}
