name: Pylint workflow

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      out:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Linting
        run: |
          pylint --output-format=json ${{inputs.path }} > ${{inputs.out}}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          path: ${{inputs.out}}
  
