name: Upload to S3

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{secrets.GITHUB_ACTION_RESULTS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.GITHUB_ACTION_RESULTS_SECRET_KEY}}
  AWS_BUCKET_NAME: ${{secrets.GITHUB_ACTION_RESULTS_BUCKET}}
  AWS_CLI_VERSION: 1.27.165

jobs:
  upload_to_S3:
    name: upload artifact to S3
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli==$AWS_CLI_VERSION 

      - name: upload to S3
        run: |
          echo "this is from github runner" > artifact.txt
          aws --version
          aws s3 cp artifact.txt s3://${AWS_BUCKET_NAME}/artifact.txt

        